using DrawLiar;
using DrawLiar.Server;
using DrawLiar.GameServer;

var builder = WebApplication.CreateBuilder(args);
if (builder.Configuration["urls"] == null) builder.WebHost.UseUrls("http://127.0.0.1:19060");
ServerRuntime.Configure(builder);
ServerRuntime.RequirePublicHttps(builder, "GameServer:PublicUrl");
builder.Services.AddSingleton<MainRegistration>();
builder.Services.AddHostedService(services => services.GetRequiredService<MainRegistration>());
var app = builder.Build();
await ServerRuntime.InitializeAsync(app, false);
app.MapGet("/health", (MainRegistration registration) => registration.IsReady ? Results.Ok(new { Status = "Ready" }) : Results.StatusCode(503));
var database = app.Services.GetRequiredService<ServerDatabase>();
string nodeId = app.Configuration["GameServer:NodeId"] ?? throw new InvalidOperationException("GameServer:NodeId가 필요합니다.");
Task<ServerSession> Authenticate(HttpContext context) => database.AuthenticateAsync(ServerRuntime.Bearer(context), "game:" + nodeId);

app.MapPost("/api/session/enter", (EnterGameRequest request) => database.EnterGameAsync(request.AssignmentToken, nodeId));
app.MapPost("/api/session/logout", (Func<HttpContext, Task<IResult>>)(async context => { await database.LogoutAsync(await Authenticate(context)); return Results.NoContent(); }));
app.MapGet("/api/profile", (Func<HttpContext, Task<ProfileData>>)(async context => await database.ProfileAsync((await Authenticate(context)).AccountId)));
app.MapPatch("/api/profile", async (HttpContext context, UpdateProfileRequest request) => await database.UpdateProfileAsync((await Authenticate(context)).AccountId, request));
app.MapGet("/api/friends", (Func<HttpContext, Task<FriendListResponse>>)(async context => await database.FriendsAsync((await Authenticate(context)).AccountId)));
app.MapPost("/api/friends/request", async (HttpContext context, FriendRequest request) => { await database.RequestFriendAsync((await Authenticate(context)).AccountId, ServerRuntime.AccountId(request.AccountId)); return Results.NoContent(); });
app.MapPost("/api/friends/respond", async (HttpContext context, FriendRespondRequest request) => { await database.RespondFriendAsync((await Authenticate(context)).AccountId, ServerRuntime.AccountId(request.AccountId), request.Accept); return Results.NoContent(); });
app.MapDelete("/api/friends/{accountId}", async (HttpContext context, string accountId) => { await database.RemoveFriendAsync((await Authenticate(context)).AccountId, ServerRuntime.AccountId(accountId)); return Results.NoContent(); });
app.MapGet("/api/shop", (Func<HttpContext, Task<ShopResponse>>)(async context => { await Authenticate(context); return new ShopResponse { Products = ServerDatabase.ShopProducts }; }));
app.MapPost("/api/shop/purchase", async (HttpContext context, PurchaseRequest request) => await database.PurchaseAsync((await Authenticate(context)).AccountId, request));
app.MapGet("/api/rooms", async (HttpContext context, string? search) => { await Authenticate(context); return await database.RoomsAsync(search); });
app.MapPost("/api/rooms", async (HttpContext context, CreateRoomRequest request) => await database.CreateRoomAsync(await Authenticate(context), request));
app.MapPost("/api/rooms/{roomId}/join", async (HttpContext context, string roomId, JoinRoomRequest request) => await database.JoinRoomAsync(await Authenticate(context), roomId, request.AsSpectator)).RequireRateLimiting("room-join");
app.MapPost("/internal/dedicated/register", async (HttpContext context, RegisterDedicatedRequest request) => { ServerRuntime.RequireCluster(context, app.Configuration); await database.RegisterDedicatedAsync(request, app.Environment.IsDevelopment()); return Results.NoContent(); });
app.MapPost("/internal/dedicated/heartbeat", async (HttpContext context, DedicatedHeartbeatRequest request) => { ServerRuntime.RequireCluster(context, app.Configuration); return await database.DedicatedHeartbeatAsync(request); });
app.MapPost("/internal/tickets/redeem", async (HttpContext context, RedeemTicketRequest request) => { ServerRuntime.RequireCluster(context, app.Configuration); return await database.RedeemTicketAsync(request); });
app.MapPost("/internal/sessions/check", async (HttpContext context, SessionCheckRequest request) => { ServerRuntime.RequireCluster(context, app.Configuration); return new SessionCheckResponse { Valid = await database.CheckDedicatedSessionAsync(request) }; });
await app.RunAsync();
