location = /drawliar/admin {
    return 308 /drawliar/admin/;
}
location ^~ /drawliar/admin/ {
    proxy_pass https://34.158.195.192:19080/;
    include /etc/nginx/snippets/rascallab-drawliar-proxy.conf;
    proxy_cache off;
}
